# Configuración básica
title: "Gastón Mercaú - Currículum Profesional"
email: grmercau@gmail.com
description: "Desarrollador Web con X años de experiencia"
baseurl: "" 
url: "https://gmercau.github.io"

# Selección del tema (cambia 'minima' por el que prefieras)
theme: jekyll-theme-cayman

# Configuraciones específicas del tema (opcional)
jekyll-theme-cayman:
  # Color de cabecera (puede ser: default, dark, primary)
  header_theme: dark
  # Mostrar enlaces en el pie de página
  show_footer_links: false

# Habilita la inclusión de CSS/JS
plugins:
  - jekyll-sass-converter
  - jekyll-seo-tag
