# Configuración básica
title: "Gastón Mercaú - Currículum"
email: grmercau@gmail.com
description: "Desarrollador Web"
baseurl: "" 
url: "https://gmercau.github.io"

# Selección del tema 
theme: jekyll-theme-cayman

# Configuraciones específicas del tema 
jekyll-theme-cayman:
  # Color de cabecera 
  header_theme: dark
  # Mostrar enlaces en el pie de página
  show_footer_links: false

# Habilita la inclusión de CSS/JS
plugins:
  - jekyll-sass-converter
  - jekyll-seo-tag
